package core

// vertexAIModelCatalog contains official models hosted or served via Google Vertex AI / AI Studio.
var vertexAIModelCatalog = map[ModelID]ModelInfo{
	ModelGemini25Pro: {
		Provider:            ProviderVertexAI,
		Vendor:              "Google",
		Name:                "Gemini 2.5 Pro",
		ID:                  ModelGemini25Pro,
		InputUSDPerMillion:  1.25,
		OutputUSDPerMillion: 5.00,
		CacheDiscountRate:   0.75, // 75% OFF
		SourceLabel:         "Google Gemini 2.5 Pro pricing",
		SourceURL:           "https://ai.google.dev/gemini-api/docs/pricing",
	},
	ModelGemini25Flash: {
		Provider:            ProviderVertexAI,
		Vendor:              "Google",
		Name:                "Gemini 2.5 Flash",
		ID:                  ModelGemini25Flash,
		InputUSDPerMillion:  0.30,
		OutputUSDPerMillion: 2.50,
		CacheDiscountRate:   0.90, // 90% OFF
		SourceLabel:         "Google Gemini 2.5 Flash pricing",
		SourceURL:           "https://ai.google.dev/gemini-api/docs/pricing",
	},
	ModelGemini37Flash: {
		Provider:            ProviderVertexAI,
		Vendor:              "Google",
		Name:                "Gemini 3.7 Flash",
		ID:                  ModelGemini37Flash,
		InputUSDPerMillion:  0.75,
		OutputUSDPerMillion: 3.75,
		CacheDiscountRate:   0.90, // 90% OFF
		SourceLabel:         "Google Gemini Developer API paid standard pricing",
		SourceURL:           "https://ai.google.dev/gemini-api/docs/pricing",
	},
	ModelGemini38Flash: {
		Provider:            ProviderVertexAI,
		Vendor:              "Google",
		Name:                "Gemini 3.8 Flash",
		ID:                  ModelGemini38Flash,
		InputUSDPerMillion:  0.75,
		OutputUSDPerMillion: 3.75,
		CacheDiscountRate:   0.90,
		SourceLabel:         "Google Gemini Developer API paid standard pricing",
		SourceURL:           "https://ai.google.dev/gemini-api/docs/pricing",
	},
	ModelGemini37FlashHigh: {
		Provider:            ProviderVertexAI,
		Vendor:              "Google",
		Name:                "Gemini 3.7 Flash High",
		ID:                  ModelGemini37FlashHigh,
		InputUSDPerMillion:  0.75,
		OutputUSDPerMillion: 3.00,
		CacheDiscountRate:   0.90,
		SourceLabel:         "Gemini Flash High pricing policy",
	},
	ModelGemini37FlashSafety: {
		Provider:            ProviderVertexAI,
		Vendor:              "Google",
		Name:                "Gemini 3.7 Flash Safety LE",
		ID:                  ModelGemini37FlashSafety,
		IsFree:              true,
		SourceLabel:         "Antigravity safety model policy",
	},
	ModelClaudeSonnet46: {
		Provider:            ProviderVertexAI,
		Vendor:              "Anthropic",
		Name:                "Claude Sonnet 4.6",
		ID:                  ModelClaudeSonnet46,
		InputUSDPerMillion:  3.30,
		OutputUSDPerMillion: 15.00,
		CacheDiscountRate:   0.90, // 90% OFF
		SourceLabel:         "Claude Sonnet standard pricing",
		SourceURL:           "https://cloud.google.com/gemini-enterprise-agent-platform/generative-ai/pricing",
	},
	ModelClaude37Sonnet: {
		Provider:            ProviderVertexAI,
		Vendor:              "Anthropic",
		Name:                "Claude 3.7 Sonnet",
		ID:                  ModelClaude37Sonnet,
		InputUSDPerMillion:  3.00,
		OutputUSDPerMillion: 15.00,
		CacheDiscountRate:   0.90,
		SourceLabel:         "Claude Sonnet standard pricing",
		SourceURL:           "https://cloud.google.com/gemini-enterprise-agent-platform/generative-ai/pricing",
	},
	ModelClaude35Sonnet: {
		Provider:            ProviderVertexAI,
		Vendor:              "Anthropic",
		Name:                "Claude 3.5 Sonnet",
		ID:                  ModelClaude35Sonnet,
		InputUSDPerMillion:  3.00,
		OutputUSDPerMillion: 15.00,
		CacheDiscountRate:   0.90,
		SourceLabel:         "Claude Sonnet standard pricing",
		SourceURL:           "https://cloud.google.com/gemini-enterprise-agent-platform/generative-ai/pricing",
	},
}
